---
title: "Information on Site Class Identifier"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
```

# Instructions
This function allows the user to upload station information and assigns natural StreamCat factors. Some metrics are adjusted based on site-specific StreamCat estimates. **See Background tab for metric calculations.** Note, there are approximately 50 COMIDs in WY with some missing StreamCat data. Missing adjustment factor data will cause IBI scores to be incorrectly calculated. So, we recommend inputing an estimate from a nearby, similarly sized COMID. **Elevation (ft)** is also a metric adjustment factor, but elevation estimates are not provided in this tab, and so, must be provided by the user.

Follow the steps to the left to upload a site & COMID table. For more information on the derivation of these metric adjustment factors, please read the [WDEQ Diatom IBI report](https://github.com/Blocktt/ShinyAppDocuments/tree/main/WDEQtools/Reports). Feel free to download an [Example file](https://github.com/Blocktt/ShinyAppDocuments/tree/main/WDEQtools/Example_Files) to understand how the function works.
